---
- name: Deploy vimrc
  hosts: all
  become: true

  tasks:
    
    - name: Copy .vimrc file to home directory
      ansible.builtin.template:
        src: vimrc.j2
        dest: /home/valenzsx/.vimrc