---
- name: Deploy vimrc
  hosts: all

  tasks:
    
    - name: Copy .vimrc file to home directory
      ansible.builtin.file:
        src: .vimrc
        dest: "/home/{{ item }}/.vimrc"
      loop:
        - valenzsx